name: tom_tools
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  pointycastle:
  asn1lib:
  cryptography: ^2.9.0
  tom_crypto:
    path: ../tom_crypto

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
